development: &non_production_settings
  :semantictweet:
    :base_uri: http://semantictweet.com
    :generator_agent: http://semantictweet.com/
    :error_reports_to: mailto:stephen@flinter.com

  :twitter:
    :base_uri: api.twitter.com
    :search_uri: http://search.twitter.com
    :api_version: 1
    :basic_auth_username: semantictweet
    :basic_auth_password: secret

  :geonames:
    :base_uri: ws.geonames.org
    :sws_base_uri: sws.geonames.org

test:
  <<: *non_production_settings
  :semantictweet:
    :base_uri: http://semantictweet.local

production:
  <<: *non_production_settings
